/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Modelo.Vendedor;
import Modelo.VendedorDAO;
import Modelo.Ventas;
import Modelo.VentasDao;
import java.awt.event.ActionEvent;
import java.util.ArrayList;

/**
 *
 * @author hotpc
 */
public class VentanaVenta extends javax.swing.JFrame {

    /**
     * Creates new form VentanaVenta
     */
    public VentanaVenta() {
        initComponents();
        VentasDao cd = new VentasDao();
           ArrayList<Vendedor>vendedores = cd.getVendedores();
        for (int i = 0; i < vendedores.size(); i++) {
            Vendedor p = vendedores.get(i);
          vendedorCx.addItem(p);
     
    }
          registrarBt.addActionListener(e -> {
            Actualizar(e);
        });
  
    
   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        vendedorCx = new javax.swing.JComboBox<>();
        sucursalCx = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        fechaTf = new javax.swing.JTextField();
        montoTf = new javax.swing.JTextField();
        registrarBt = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Vendedor");

        jLabel2.setText("Sucursal");

        vendedorCx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vendedorCxActionPerformed(evt);
            }
        });

        sucursalCx.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Centro", "Portal Temuco", " ", " " }));

        jLabel3.setText("Fecha");

        jLabel4.setText("Monto");

        montoTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                montoTfActionPerformed(evt);
            }
        });

        registrarBt.setText("Registrar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(vendedorCx, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(sucursalCx, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(fechaTf, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(montoTf, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(122, 122, 122))
            .addGroup(layout.createSequentialGroup()
                .addGap(125, 125, 125)
                .addComponent(registrarBt)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(vendedorCx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(sucursalCx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(fechaTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(montoTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(registrarBt)
                .addGap(17, 17, 17))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void montoTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_montoTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_montoTfActionPerformed

    private void vendedorCxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vendedorCxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vendedorCxActionPerformed

    /**
     * @param args the command line arguments
     */
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField fechaTf;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField montoTf;
    private javax.swing.JButton registrarBt;
    private javax.swing.JComboBox<String> sucursalCx;
    private javax.swing.JComboBox<Vendedor> vendedorCx;
    // End of variables declaration//GEN-END:variables

    private void Actualizar(ActionEvent e) {
        
        
        VendedorDAO pd = new VendedorDAO();
       // int idBD = idTf.getText().length();
        String sucursalBD = sucursalCx.getSelectedItem().toString();
        int montoBD = Integer.parseInt(montoTf.getText());
       // int codigoBD = Integer.parseInt(codigoTf.getText());
        String fechaBD = fechaTf.getText();
        Ventas v = new Ventas(sucursalBD, montoBD, fechaBD);
        pd.inserVentas(v);
        
        
        
        
    }

  
}
